In [1]:
import numpy as np
np.random.seed(45)
import pandas as pd
pd.options.display.max_columns 
pd.options.display.max_rows
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()

## Loading data set
### [data source](https://www.kaggle.com/sarvasaga/airbnb-singapore-listing)

___

In [2]:
data_path = r'C:\Users\DucTRung\Desktop\data_set\airbnb_singapore'

In [3]:
listing = pd.read_csv(data_path+'\\airbnb_listing.csv', encoding='ISO-8859-1')
review = pd.read_csv(data_path+'\\reviews_airbnb.csv', encoding='ISO-8859-1')

C:\Users\DucTRung\Anaconda3\envs\cc_env\lib\site-packages\IPython\core\interactiveshell.py:3051: DtypeWarning: Columns (40,41,87,88) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [4]:
listing.head()

,id,listing_url,scrape_id,last_scraped,name,summary,space,description,experiences_offered,neighborhood_overview,...,jurisdiction_names,instant_bookable,is_business_travel_ready,require_guest_profile_picture,require_guest_phone_verification,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,49091,https://www.airbnb.com/rooms/49091,20190625153033,43641,COZICOMFORT LONG TERM STAY ROOM 2,NaN,This is Room No. 2.(available after Jan 15 201...,This is Room No. 2.(available after Jan 15 201...,none,NaN,...,NaN,f,f,t,t,2,0,2,0,0.01
1,50646,https://www.airbnb.com/rooms/50646,20190625153033,43641,Pleasant Room along Bukit Timah,Fully furnished bedroom with a nice view on th...,"Good Condition room, bright & windy. Comes wit...",Fully furnished bedroom with a nice view on th...,none,The serenity & quiet surrounding makes it an i...,...,NaN,f,f,f,t,1,0,1,0,0.28
2,56334,https://www.airbnb.com/rooms/56334,20190625153033,43641,COZICOMFORT,NaN,This is Room no. 1. USD700 per month On the fa...,This is Room no. 1. USD700 per month On the fa...,none,NaN,...,NaN,f,f,t,t,2,0,2,0,0.21
3,71609,https://www.airbnb.com/rooms/71609,20190625153033,43641,Ensuite Room (Room 1 & 2) near EXPO,For 3 (Website hidden by Airbnb) room 1&2 and ...,Landed Homestay Room for Rental. Between Simei...,For 3 (Website hidden by Airbnb) room 1&2 and ...,none,NaN,...,NaN,t,f,f,t,9,0,9,0,0.13
4,71896,https://www.airbnb.com/rooms/71896,20190625153033,43641,B&B Room 1 near Airport & EXPO,NaN,Vocational Stay Deluxe Bedroom in Singapore.(N...,Vocational Stay Deluxe Bedroom in Singapore.(N...,none,NaN,...,NaN,t,f,f,t,9,0,9,0,0.21

In [5]:
review.head()

,listing_id,id,date,reviewer_id,reviewer_name,comments
0,49091,8243238,21/10/2013,8557223,Jared,Fran was absolutely gracious and welcoming. Ma...
1,50646,11909864,18/4/2014,1356099,James,A comfortable room in a smart condo developmen...
2,50646,13823948,5/6/2014,15222393,Welli,Stayed over at Sujatha's house for 3 good nigh...
3,50646,15117222,2/7/2014,5543172,Cyril,It's been a lovely stay at Sujatha's. The room...
4,50646,15426462,8/7/2014,817532,Jake,"We had a great experience. A nice place, an am..."

In [13]:
listing.loc[0]

id                                                                           49091
listing_url                                     https://www.airbnb.com/rooms/49091
scrape_id                                                           20190625153033
last_scraped                                                                 43641
name                                             COZICOMFORT LONG TERM STAY ROOM 2
                                                               ...
calculated_host_listings_count                                                   2
calculated_host_listings_count_entire_homes                                      0
calculated_host_listings_count_private_rooms                                     2
calculated_host_listings_count_shared_rooms                                      0
reviews_per_month                                                             0.01
Name: 0, Length: 98, dtype: object