In [1]:
import pandas as pd
import numpy as np
from IPython.display import display
from datetime import datetime
pd.set_option('display.max_columns', None)

## Loading Datasets

In [2]:
_path = r'C:\Users\DucTRung\Desktop\My_Projects\European_Footboll\data_set\soccer'

### match

In [3]:
match_df = pd.read_csv(_path + '\Match.csv', sep='\t')

In [4]:
display(match_df.head())

,id,country_id,league_id,season,stage,date,match_api_id,home_team_api_id,away_team_api_id,home_team_goal,away_team_goal,home_player_X1,home_player_X2,home_player_X3,home_player_X4,home_player_X5,home_player_X6,home_player_X7,home_player_X8,home_player_X9,home_player_X10,home_player_X11,away_player_X1,away_player_X2,away_player_X3,away_player_X4,away_player_X5,away_player_X6,away_player_X7,away_player_X8,away_player_X9,away_player_X10,away_player_X11,home_player_Y1,home_player_Y2,home_player_Y3,home_player_Y4,home_player_Y5,home_player_Y6,home_player_Y7,home_player_Y8,home_player_Y9,home_player_Y10,home_player_Y11,away_player_Y1,away_player_Y2,away_player_Y3,away_player_Y4,away_player_Y5,away_player_Y6,away_player_Y7,away_player_Y8,away_player_Y9,away_player_Y10,away_player_Y11,home_player_1,home_player_2,home_player_3,home_player_4,home_player_5,home_player_6,home_player_7,home_player_8,home_player_9,home_player_10,home_player_11,away_player_1,away_player_2,away_player_3,away_player_4,away_player_5,away_player_6,away_player_7,away_player_8,away_player_9,away_player_10,away_player_11,goal,shoton,shotoff,foulcommit,card,cross,corner,possession,B365H,B365D,B365A,BWH,BWD,BWA,IWH,IWD,IWA,LBH,LBD,LBA,PSH,PSD,PSA,WHH,WHD,WHA,SJH,SJD,SJA,VCH,VCD,VCA,GBH,GBD,GBA,BSH,BSD,BSA
0,1,1,1,2008/2009,1,2008-08-17 00:00:00,492473,9987,9993,1,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.73,3.40,5.00,1.75,3.35,4.20,1.85,3.2,3.5,1.80,3.3,3.75,NaN,NaN,NaN,1.70,3.30,4.33,1.90,3.3,4.00,1.65,3.40,4.50,1.78,3.25,4.00,1.73,3.40,4.20
1,2,1,1,2008/2009,1,2008-08-16 00:00:00,492474,10000,9994,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.95,3.20,3.60,1.80,3.30,3.95,1.90,3.2,3.5,1.90,3.2,3.50,NaN,NaN,NaN,1.83,3.30,3.60,1.95,3.3,3.80,2.00,3.25,3.25,1.85,3.25,3.75,1.91,3.25,3.60
2,3,1,1,2008/2009,1,2008-08-16 00:00:00,492475,9984,8635,0,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.38,3.30,2.75,2.40,3.30,2.55,2.60,3.1,2.3,2.50,3.2,2.50,NaN,NaN,NaN,2.50,3.25,2.40,2.63,3.3,2.50,2.35,3.25,2.65,2.50,3.20,2.50,2.30,3.20,2.75
3,4,1,1,2008/2009,1,2008-08-17 00:00:00,492476,9991,9998,5,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.44,3.75,7.50,1.40,4.00,6.80,1.40,3.9,6.0,1.44,3.6,6.50,NaN,NaN,NaN,1.44,3.75,6.00,1.44,4.0,7.50,1.45,3.75,6.50,1.50,3.75,5.50,1.44,3.75,6.50
4,5,1,1,2008/2009,1,2008-08-16 00:00:00,492477,7947,9985,1,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.00,3.50,1.65,5.00,3.50,1.60,4.00,3.3,1.7,4.00,3.4,1.72,NaN,NaN,NaN,4.20,3.40,1.70,4.50,3.5,1.73,4.50,3.40,1.65,4.50,3.50,1.65,4.75,3.30,1.67

### player_attributes

In [5]:
player_df = pd.read_csv(_path + '\Player_Attributes.csv', sep='\t')

In [6]:
player_df.head()

,id,player_fifa_api_id,player_api_id,date,overall_rating,potential,preferred_foot,attacking_work_rate,defensive_work_rate,crossing,finishing,heading_accuracy,short_passing,volleys,dribbling,curve,free_kick_accuracy,long_passing,ball_control,acceleration,sprint_speed,agility,reactions,balance,shot_power,jumping,stamina,strength,long_shots,aggression,interceptions,positioning,vision,penalties,marking,standing_tackle,sliding_tackle,gk_diving,gk_handling,gk_kicking,gk_positioning,gk_reflexes
0,1,218353,505942,2016-02-18 00:00:00,67.0,71.0,right,medium,medium,49.0,44.0,71.0,61.0,44.0,51.0,45.0,39.0,64.0,49.0,60.0,64.0,59.0,47.0,65.0,55.0,58.0,54.0,76.0,35.0,71.0,70.0,45.0,54.0,48.0,65.0,69.0,69.0,6.0,11.0,10.0,8.0,8.0
1,2,218353,505942,2015-11-19 00:00:00,67.0,71.0,right,medium,medium,49.0,44.0,71.0,61.0,44.0,51.0,45.0,39.0,64.0,49.0,60.0,64.0,59.0,47.0,65.0,55.0,58.0,54.0,76.0,35.0,71.0,70.0,45.0,54.0,48.0,65.0,69.0,69.0,6.0,11.0,10.0,8.0,8.0
2,3,218353,505942,2015-09-21 00:00:00,62.0,66.0,right,medium,medium,49.0,44.0,71.0,61.0,44.0,51.0,45.0,39.0,64.0,49.0,60.0,64.0,59.0,47.0,65.0,55.0,58.0,54.0,76.0,35.0,63.0,41.0,45.0,54.0,48.0,65.0,66.0,69.0,6.0,11.0,10.0,8.0,8.0
3,4,218353,505942,2015-03-20 00:00:00,61.0,65.0,right,medium,medium,48.0,43.0,70.0,60.0,43.0,50.0,44.0,38.0,63.0,48.0,60.0,64.0,59.0,46.0,65.0,54.0,58.0,54.0,76.0,34.0,62.0,40.0,44.0,53.0,47.0,62.0,63.0,66.0,5.0,10.0,9.0,7.0,7.0
4,5,218353,505942,2007-02-22 00:00:00,61.0,65.0,right,medium,medium,48.0,43.0,70.0,60.0,43.0,50.0,44.0,38.0,63.0,48.0,60.0,64.0,59.0,46.0,65.0,54.0,58.0,54.0,76.0,34.0,62.0,40.0,44.0,53.0,47.0,62.0,63.0,66.0,5.0,10.0,9.0,7.0,7.0

In [10]:
player_df['overall_rating'].value_counts()

68.0    10492
69.0    10281
67.0    10198
66.0    10112
70.0    10028
        ...
38.0        8
35.0        5
36.0        3
37.0        3
33.0        2
Name: overall_rating, Length: 61, dtype: int64

## What is the connector between three table above?
#### home_player_x

In [25]:
# def get_home_overall_rating(match, player):
    
#     match_date = pd.to_datetime(match['date'])
#     player_date = pd.to_datetime(player['date'])
    
#     list_player_id = []
#     for i in range(1, 12):
#         x = 'home_player_'+str(i)
#         player_id = match[x]
#         list_player_id.append(player_id)
    
#     player = player[player['player_api_id'].isin(list_player_id)]
#     player['date'] = pd.to_datetime(player['date'], format='%Y-%m-%d')
#     player['diff_date'] = abs((match_data - player_date).dt.days)
#     player = player.sort_value('diff_date').drop_duplicates('player_api_id', keep= first)

In [33]:
# att = match_df.apply(lambda x : get_home_overall_rating(x, player_df), axis=1)

## Remove not important data
### match

In [27]:
for i, e in enumerate(match_df.columns):
    print(i,':',e)

0 : id
1 : country_id
2 : league_id
3 : season
4 : stage
5 : date
6 : match_api_id
7 : home_team_api_id
8 : away_team_api_id
9 : home_team_goal
10 : away_team_goal
11 : home_player_X1
12 : home_player_X2
13 : home_player_X3
14 : home_player_X4
15 : home_player_X5
16 : home_player_X6
17 : home_player_X7
18 : home_player_X8
19 : home_player_X9
20 : home_player_X10
21 : home_player_X11
22 : away_player_X1
23 : away_player_X2
24 : away_player_X3
25 : away_player_X4
26 : away_player_X5
27 : away_player_X6
28 : away_player_X7
29 : away_player_X8
30 : away_player_X9
31 : away_player_X10
32 : away_player_X11
33 : home_player_Y1
34 : home_player_Y2
35 : home_player_Y3
36 : home_player_Y4
37 : home_player_Y5
38 : home_player_Y6
39 : home_player_Y7
40 : home_player_Y8
41 : home_player_Y9
42 : home_player_Y10
43 : home_player_Y11
44 : away_player_Y1
45 : away_player_Y2
46 : away_player_Y3
47 : away_player_Y4
48 : away_player_Y5
49 : away_player_Y6
50 : away_player_Y7
51 : away_player_Y8
52 : away_player_Y9
53 : away_player_Y10
54 : away_player_Y11
55 : home_player_1
56 : home_player_2
57 : home_player_3
58 : home_player_4
59 : home_player_5
60 : home_player_6
61 : home_player_7
62 : home_player_8
63 : home_player_9
64 : home_player_10
65 : home_player_11
66 : away_player_1
67 : away_player_2
68 : away_player_3
69 : away_player_4
70 : away_player_5
71 : away_player_6
72 : away_player_7
73 : away_player_8
74 : away_player_9
75 : away_player_10
76 : away_player_11
77 : goal
78 : shoton
79 : shotoff
80 : foulcommit
81 : card
82 : cross
83 : corner
84 : possession
85 : B365H
86 : B365D
87 : B365A
88 : BWH
89 : BWD
90 : BWA
91 : IWH
92 : IWD
93 : IWA
94 : LBH
95 : LBD
96 : LBA
97 : PSH
98 : PSD
99 : PSA
100 : WHH
101 : WHD
102 : WHA
103 : SJH
104 : SJD
105 : SJA
106 : VCH
107 : VCD
108 : VCA
109 : GBH
110 : GBD
111 : GBA
112 : BSH
113 : BSD
114 : BSA

In [30]:
match_df = match_df[match_df.columns[0:77]]

In [34]:
match_df = match_df.drop(match_df.columns[11:55], axis=1)

In [35]:
match_df

,id,country_id,league_id,season,stage,date,match_api_id,home_team_api_id,away_team_api_id,home_team_goal,away_team_goal,home_player_1,home_player_2,home_player_3,home_player_4,home_player_5,home_player_6,home_player_7,home_player_8,home_player_9,home_player_10,home_player_11,away_player_1,away_player_2,away_player_3,away_player_4,away_player_5,away_player_6,away_player_7,away_player_8,away_player_9,away_player_10,away_player_11
0,1,1,1,2008/2009,1,2008-08-17 00:00:00,492473,9987,9993,1,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,1,1,2008/2009,1,2008-08-16 00:00:00,492474,10000,9994,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,1,1,2008/2009,1,2008-08-16 00:00:00,492475,9984,8635,0,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,1,1,2008/2009,1,2008-08-17 00:00:00,492476,9991,9998,5,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5,1,1,2008/2009,1,2008-08-16 00:00:00,492477,7947,9985,1,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25974,25975,24558,24558,2015/2016,9,2015-09-22 00:00:00,1992091,10190,10191,1,0,42231.0,678384.0,95220.0,638592.0,413155.0,45780.0,171229.0,67333.0,119839.0,143790.0,195215.0,462944.0,563066.0,8800.0,67304.0,158253.0,133126.0,186524.0,93223.0,121115.0,232110.0,289732.0
25975,25976,24558,24558,2015/2016,9,2015-09-23 00:00:00,1992092,9824,10199,1,2,33272.0,41621.0,25813.0,257845.0,114735.0,42237.0,113227.0,358156.0,32343.0,531309.0,37257.0,42276.0,114792.0,150007.0,178119.0,27232.0,570830.0,260708.0,201704.0,36382.0,34082.0,95257.0
25976,25977,24558,24558,2015/2016,9,2015-09-23 00:00:00,1992093,9956,10179,2,0,157856.0,274779.0,177689.0,294256.0,42258.0,39979.0,173936.0,147959.0,451983.0,80564.0,289472.0,10637.0,67349.0,202663.0,32597.0,114794.0,188114.0,25840.0,482200.0,95230.0,451335.0,275122.0
25977,25978,24558,24558,2015/2016,9,2015-09-22 00:00:00,1992094,7896,10243,0,0,NaN,8881.0,173534.0,39646.0,282287.0,340790.0,393337.0,8893.0,614454.0,93229.0,178142.0,274776.0,121080.0,197757.0,260964.0,231614.0,113235.0,41116.0,462608.0,42262.0,92252.0,194532.0
25978,25979,24558,24558,2015/2016,9,2015-09-23 00:00:00,1992095,10192,9931,4,3,274787.0,492132.0,108451.0,25815.0,94553.0,384376.0,598355.0,36785.0,45174.0,302079.0,71764.0,156175.0,95216.0,172768.0,22834.0,458806.0,207234.0,25772.0,40274.0,34035.0,41726.0,527103.0

### player attributes

In [46]:
for e, i in enumerate(player_df.columns):
    print(e, ':', i)

0 : id
1 : player_fifa_api_id
2 : player_api_id
3 : date
4 : overall_rating
5 : potential
6 : preferred_foot
7 : attacking_work_rate
8 : defensive_work_rate
9 : crossing
10 : finishing
11 : heading_accuracy
12 : short_passing
13 : volleys
14 : dribbling
15 : curve
16 : free_kick_accuracy
17 : long_passing
18 : ball_control
19 : acceleration
20 : sprint_speed
21 : agility
22 : reactions
23 : balance
24 : shot_power
25 : jumping
26 : stamina
27 : strength
28 : long_shots
29 : aggression
30 : interceptions
31 : positioning
32 : vision
33 : penalties
34 : marking
35 : standing_tackle
36 : sliding_tackle
37 : gk_diving
38 : gk_handling
39 : gk_kicking
40 : gk_positioning
41 : gk_reflexes

In [48]:
overall_player = player_df[['date', 'player_api_id', 'overall_rating']]

In [49]:
overall_player.to_csv('overall.csv', index=False)

In [50]:
pd.read_csv(r'C:\Users\DucTRung\Desktop\My_Projects\European_Footboll\overall.csv')

                       date  player_api_id  overall_rating
0       2016-02-18 00:00:00         505942            67.0
1       2015-11-19 00:00:00         505942            67.0
2       2015-09-21 00:00:00         505942            62.0
3       2015-03-20 00:00:00         505942            61.0
4       2007-02-22 00:00:00         505942            61.0
...                     ...            ...             ...
183973  2009-08-30 00:00:00          39902            83.0
183974  2009-02-22 00:00:00          39902            78.0
183975  2008-08-30 00:00:00          39902            77.0
183976  2007-08-30 00:00:00          39902            78.0
183977  2007-02-22 00:00:00          39902            80.0

[183978 rows x 3 columns]

## Merge 'match' and 'overall' df